[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rhs"
authors = []
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version", "description"]
